config/urls.py
from django.contrib import admin
from django.urls import path, include
from tcatcc import views as tcatccviews

urlpatterns = [
	path('', include('tcatcc.urls')),
    path('admin/', admin.site.urls),
    path('accounts/signup', tcatccviews.signUp, name='sign-up'),
    path('accounts/', include('django.contrib.auth.urls')),
]

tcatcc/urls.py
from django.urls import path
from . import views

app_name = 'tcatcc'
urlpatterns = [
	path('', views.index, name="index"),
	path('new', views.newItemView, name="create-item"),
	path('<int:itemid>', views.detailItemView, name="item-detail"),
	path('<uuid:uuid>', views.confirmSignupView, name="signup-confirmation")
]

tcatcc/models.py
from django.db import models
from django.utils import timezone
import uuid, datetime

from django.contrib.auth.models import User

from django.core.mail import send_mail

# Create your models here.
class Item(models.Model):
	name = models.TextField()
	description = models.TextField()
	owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

	threshold = models.IntegerField()
	expiryDate =  models.DateTimeField(blank=True,null=True)

	stillOpen = models.BooleanField(default=True)

	def __str__(self):
		return self.name

	def agreers(self):
		return self.agreement_set.count()

	def checkAndSendEmails(self):
		if self.agreers() >= self.threshold and (self.expiryDate is None or self.expiryDate >= timezone.now()) and self.stillOpen:
			self.sendEmails()

	def sendEmails(self):
		send_mail(
			'TCATCC Alert',
			'The item %s with description %s has met its threshold; act accordingly.' %(self.name,self.description),
			'diamond-grouping@example.com',
			list(Agreement.objects.filter(item=self)),
		)
		self.stillOpen = False
		self.save()

class Agreement(models.Model):
	email = models.EmailField()
	item = models.ForeignKey(Item, on_delete=models.CASCADE)

	def __str__(self):
		return "%s signup to %s" %(self.email, self.item.name)

	def save(self,*args,**kwargs):
		super().save(*args, **kwargs)
		self.item.checkAndSendEmails()

class AgreementRequest(models.Model):
	id = models.UUIDField(primary_key=True,default=uuid.uuid4, editable=False)
	email = models.EmailField()
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	creationDate = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "Token"

	def expired(self):
		return (timezone.now() - creationDate).total_seconds() > 86400;

	def validate(self,*args,**kwargs):
		agreement = Agreement()
		if Agreement.objects.filter(email=self.email).filter(item=self.item).count() == 0: 
			agreement.email = self.email
			agreement.item = self.item
			agreement.save()
		self.delete()

	def save(self,*args,**kwargs):
		send_mail(
			'TCATCC Alert',
			"You've signed up to %s, chungus."%(self.pk),
			'diamond-grouping@example.com',
			[self.email]
		)

		AgreementRequest.objects.filter(creationDate__lte=(timezone.now()-datetime.timedelta(days=1))).delete()

		super().save(*args,**kwargs)

tcatcc/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
import html5.forms.widgets as html5_widgets

from .models import Item, Agreement

class createItemForm(forms.ModelForm):
	class Meta:
		model = Item
		fields = ['name', 'description', 'threshold', 'expiryDate']
		labels = {
			'expiryDate': _('Expiry Date')
		}

	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)
		self.fields['expiryDate'].widget = html5_widgets.DateInput()

	def clean_threshold(self):
		data = self.cleaned_data['threshold']
		if data <= 0:
			raise ValidationError(_('Threshold must be positive.'))
		return data

	def clean_expiryDate(self):
		data = self.cleaned_data['expiryDate']
		if data is not None:
			if data <= timezone.now():
				raise ValidationError(_('Expiry date must be in the future if present.'))
		return data

class subscribeForm(forms.ModelForm):
	class Meta:
		model = Agreement
		fields = ['email']

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class customUserCreationForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		model = User
		fields = UserCreationForm.Meta.fields + ('email',)

tcatcc/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.utils import timezone

from django.contrib.auth import authenticate, login

from .models import Item, AgreementRequest
from .forms import createItemForm, subscribeForm, customUserCreationForm

# Create your views here.
def index(request):
	itemlist = Item.objects.exclude(expiryDate__lt=timezone.now()).filter(stillOpen=True)
	context = {
		'items': itemlist,
	}
	return render(request,'tcatcc/index.html',context)

def newItemView(request):
	form = createItemForm()
	if request.method == "POST":

		form = createItemForm(request.POST)

		if form.is_valid():
			newItem = Item()
			newItem.name = form.cleaned_data['name']
			newItem.description = form.cleaned_data['description']

			if request.user.is_authenticated:
				newItem.owner = request.user

			newItem.threshold = form.cleaned_data['threshold']
			newItem.expiryDate = form.cleaned_data['expiryDate']

			newItem.save()
			return HttpResponseRedirect(reverse('tcatcc:index'))

	context = {
		'form': form,
	}

	return render(request,'tcatcc/item_create.html',context)

def detailItemView(request, itemid):
	item = get_object_or_404(Item,pk=itemid)
	sForm = subscribeForm()
	if request.user.is_authenticated:
		sForm.fields['email'].initial = request.user.email

	if request.method == "POST":
		sForm = subscribeForm(request.POST)
		if sForm.is_valid():
			newCommitment = AgreementRequest()
			newCommitment.item = item
			newCommitment.email = sForm.cleaned_data['email']
			newCommitment.save()

			#should actually just send you the validation email
			#and that view creates your new subscription
			return HttpResponseRedirect(reverse('tcatcc:index'))

	context = {
		'item': item,
		'subscribeForm': sForm,
	}

	return render(request,'tcatcc/item_detail.html',context)

def confirmSignupView(request, uuid):
	signup = get_object_or_404(AgreementRequest,pk=uuid)
	signup.validate()
	return HttpResponseRedirect(reverse('tcatcc:index'))

def signUp(request):
	form = customUserCreationForm()
	if request.method == "POST":
		form = customUserCreationForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			raw_password = form.cleaned_data['password1']
			email = form.cleaned_data['email']
			form.save()
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return HttpResponseRedirect(reverse('markets:index'))

	context = {
		'form':form,
	}
	
	return render(request, 'registration/sign_up.html', context)

tcatcc/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<title>{% block title %}{% endblock %}</title>
</head>

<body class="d-flex flex-column h-100">

<div class="container-fluid">
<div class="row">
	
<div class="col-sm-2">
{% block sidebar %}
{% if user.is_authenticated %} <p>Logged in as {{user}}. <a href="{% url 'logout' %}">Log out.</a></p>
{% else %}<p><a href="{% url 'login' %}">Log in.</a></p><p><a href="{% url 'sign-up' %}">Create new account.</a></p>
{% endif %}
<p><a href="{% url 'tcatcc:index' %}">Return to index.</a></p>
{% endblock %}

{% block contextualsidebar %}
{% endblock %}
</div>

<div class="col-sm-10">
{% block content %}{% endblock %}
</div>

</div>
</div>

{% if False %}
<footer class="footer">
	<div class="container">
	{% block footer %}PMarket Maker by <a href="https://twitter.com/TetraspaceAdmn">Diamond Grouping</a>{% endblock %}
	</div>
</footer>
{% endif %}

</body>

</html>

tcatcc/templates/tcatcc/index.html
{% extends "base_generic.html" %}

{% block title %}Index{% endblock %}

{% block content %}

<table class="table">
	<thead>
		<tr>
			<th scope="col">Name</th>
			<th scope="col">Description</th>
		</tr>
		{% if True %}
		<tr>
			<td colspan="2"><a href="{% url 'tcatcc:create-item' %}"><div><strong>Create new item</strong></div><a></td>
		</tr>
		{% endif %}
		<tr>
		</tr>
	</thead>
	<tbody>
		{% for item in items %}
		<tr>
			<td><a href="{% url 'tcatcc:item-detail' item.id %}"><div>{{item.name}}<br/>
			<div class="progress">
				<div class="progress-bar" role="progressbar" style="width: {% widthratio item.agreers item.threshold 100 %}%" aria-valuenow="{{item.agreers}}" aria-valuemin="0" aria-valuemax="{{item.threshold}}">{{item.agreers}}/{{item.threshold}}</div>
			</div>
			</div></a>
			</td>
			<td>{{item.description}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

tcatcc/templates/tcatcc/item_create.html
{% extends "base_generic.html" %}
{% load widget_tweaks %}

{% block title %}
<title>Create New Item</title>
{% endblock %}

{% block content %}
<h1>Create New Item</h1>

<p>
Creating a new item as {{user}}.
</p>

<form action="" method="post">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	 <div class="form-group row">
	  <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
	   <div class="col-sm-10">{% render_field field class="form-control" %}</div>
	   {% for error in field.errors %}
	    <span class="help-block">{{ error }}</span>
	   {% endfor %}
	 </div>
	{% endfor %}
	<input type="submit" class="btn btn-primary" value="Create">
</form>

{% endblock %}

tcatcc/templates/tcatcc/item_detail.html
{% extends "base_generic.html" %}
{% load widget_tweaks %}

{% block title %}
{{item.name}}
{% endblock %}

{% block content %}
<h1>{{item.name}}</h1>

<p>
{{item.description}}
</p>

<h2>Sign Up</h2>

<form action="" method="post">
	{% csrf_token %}
	{% for field in subscribeForm.visible_fields %}
	 <div class="form-group row">
	  <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
	   <div class="col-sm-10">{% render_field field class="form-control" %}</div>
	   {% for error in field.errors %}
	    <span class="help-block">{{ error }}</span>
	   {% endfor %}
	 </div>
	{% endfor %}
	<input type="submit" class="btn btn-primary" name="signupbutton" value="Sign Up">
</form>

{% endblock %}

tcatcc/templates/tcatcc/market_edit.html
{% extends "base_generic.html" %}
{% load widget_tweaks %}

{% block title %}
<title>Edit {{market.name}}</title>
{% endblock %}

{% block content %}
<h1>Edit {{market.name}}</h1>

<p>
Editing the <a href="{% url 'markets:market-detail' market.id %}">{{market.name}}</a> market.
</p>

<form action="" method="post">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	 <div class="form-group row">
	  <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
	   <div class="col-sm-10">{% render_field field class="form-control" %}</div>
	   {% for error in field.errors %}
	    <span class="help-block">{{ error }}</span>
	   {% endfor %}
	 </div>
	{% endfor %}
	<input type="submit" class="btn btn-primary" value="Edit Market">
</form>

{% endblock %}

tcatcc/templates/tcatcc/option_create.html
{% extends "base_generic.html" %}
{% load widget_tweaks %}

{% block title %}
<title>Create New Option</title>
{% endblock %}

{% block content %}
<h1>Create New Option</h1>

<p>
Creating a new option in the <a href="{%url 'markets:market-detail' market.id %}">{{market.name}}</a> market.
</p>

<form action="" method="post">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	 <div class="form-group row">
	  <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
	   <div class="col-sm-10">{% render_field field class="form-control" %}</div>
	   {% for error in field.errors %}
	    <span class="help-block">{{ error }}</span>
	   {% endfor %}
	 </div>
	{% endfor %}
	<input type="submit" class="btn btn-primary" value="Create">
</form>

<p>Options assigned to the same question will appear under the same heading in the market view. The question field may be left blank.</p>

{% endblock %}

tcatcc/templates/tcatcc/option_edit.html
{% extends "base_generic.html" %}
{% load widget_tweaks %}

{% block title %}
<title>Editing {{option}}</title>
{% endblock %}

{% block content %}
<h1>Editing {{option}}</h1>

<p>
Editing the name of the {{option.name}} option{% if option.question %} for the question {{option.question}}{% endif %}, part of the <a href="{% url 'markets:market-detail' option.market.id %}">{{option.market.name}}</a> market.
</p>

<form action="" method="post">
	{% csrf_token %}
	{% for field in editForm.visible_fields %}
	 <div class="form-group row">
	  <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
	   <div class="col-sm-10">{% render_field field class="form-control" %}</div>
	   {% for error in field.errors %}
	    <span class="help-block">{{ error }}</span>
	   {% endfor %}
	 </div>
	{% endfor %}
	<input type="submit" name="editbutton" class="btn btn-primary" value="Edit Option">
</form>

<br/>
<p>Resolve the {{option.name}} option at a certain price using the below form. This will suspend trading and pay out the resolution price for each owned share.</p>

<form action="" method="post">
	{% csrf_token %}
	{% for field in resolveForm.visible_fields %}
	 <div class="form-group row">
	  <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
	   <div class="col-sm-10">
        <div class="input-group mb-3">
         <div class="input-group-prepend">
          <span class="input-group-text">¤</span>
         </div>
	   	 {% render_field field class="form-control" %}
	   	</div>
	   </div>
	   {% for error in field.errors %}
	    <span class="help-block">{{ error }}</span>
	   {% endfor %}
	 </div>
	{% endfor %}
	<input type="submit" name="resolvebutton" class="btn btn-primary" value="Resolve Option">
</form>

{% endblock %}

tcatcc/templates/tcatcc/trade.html
{% extends "base_generic.html" %}
{% load widget_tweaks %}

{% block title %}
<title>{{option.name}}</title>
{% endblock %}

{% block contextualsidebar %}
{% if portfolio %}
Your balance in this market is ¤{{portfolio.balance}}.
{% endif %}
{% endblock %}

{% block content %}
<h1>{{option.name}}</h1>

<p>
Trading on {{option.name}}, part of the "<a href="{% url 'markets:market-detail' option.market.id %}">{{option.market.name}}</a>" market.
</p>

{% if not option.closed %}

<p>Create a Buy Order if you think that the correct price of this option is <em>above</em> your MaxPrice.</p>

<form action="" method="post">
	{% csrf_token %}
	<div class="form-group row">
	 <label for="{{ buyform.maxPrice.id_for_label }}" class="col-sm-2 col-form-label">{{ buyform.maxPrice.label }}:</label>
	  <div class="col-sm-10">
	   <div class="input-group mb-3">
        <div class="input-group-prepend">
         <span class="input-group-text">¤</span>
        </div>
	   {% render_field buyform.maxPrice class="form-control" %}
	   </div>
	  </div>
	  {% for error in buyform.maxPrice.errors %}
	   <span class="help-block">{{ error }}</span>
	  {% endfor %}
	</div>
	<div class="form-group row">
	 <label for="{{ buyform.maxNumber.id_for_label }}" class="col-sm-2 col-form-label">{{ buyform.maxNumber.label }}:</label>
	  <div class="col-sm-10">{% render_field buyform.maxNumber class="form-control" %}</div>
	  {% for error in buyform.maxNumber.errors %}
	   <span class="help-block">{{ error }}</span>
	  {% endfor %}
	</div>
	<input type="submit" class="btn btn-primary" name="buyofferbutton" value="Create Buy Order">
</form>

<br/>

<p>Create a Sell Order if you think that the correct price of this option is <em>below</em> your MinPrice.</p>

<form action="" method="post">
	{% csrf_token %}
	<div class="form-group row">
	 <label for="{{ sellform.minPrice.id_for_label }}" class="col-sm-2 col-form-label">{{ sellform.minPrice.label }}:</label>
	  <div class="col-sm-10">
	   <div class="input-group mb-3">
        <div class="input-group-prepend">
         <span class="input-group-text">¤</span>
        </div>
	   {% render_field sellform.minPrice class="form-control" %}
	   </div>
	  </div>
	  {% for error in sellform.minPrice.errors %}
	   <span class="help-block">{{ error }}</span>
	  {% endfor %}
	</div>
	<div class="form-group row">
	 <label for="{{ sellform.maxNumber.id_for_label }}" class="col-sm-2 col-form-label">{{ sellform.maxNumber.label }}:</label>
	  <div class="col-sm-10">{% render_field sellform.maxNumber class="form-control" %}</div>
	  {% for error in sellform.maxNumber.errors %}
	   <span class="help-block">{{ error }}</span>
	  {% endfor %}
	</div>
	<input type="submit" class="btn btn-primary" name="sellofferbutton" value="Create Sell Order">
</form>

<p>
Part of the "<a href="{% url 'markets:market-detail' option.market.id %}">{{option.market.name}}</a>" market.
</p>

<h2>Current Buy Orders</h2>
<ul>
{% for buyorder in buyorder_list %}
<li>{{buyorder.creator}} buying {{buyorder.maxNumber}} for ¤{{buyorder.maxPrice}}</li>
{% endfor %}
</ul>

<h2>Current Sell Orders</h2>
<ul>
{% for sellorder in sellorder_list %}
<li>{{sellorder.creator}} selling {{sellorder.maxNumber}} for ¤{{sellorder.minPrice}}</li>
{% endfor %}
</ul>

{% endif %}

{% endblock %}